spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icey
    username: root
    password: 1225
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
